name: Cloud Resume API test
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python 3.8 and pipenv
      uses: actions/setup-python@v2
      with:
        python-version: "3.8"
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install boto3
        pip install moto

        
    - name: Run tests
      run: |
        pip install pytest
        pytest tests/test_lambda.py -s -v --durations=0